//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Dal.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch
    {
        public int ID { get; set; }
        public Nullable<int> FK_FileDocumentID { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<int> ToAgency { get; set; }
        public Nullable<int> AnswerAgency { get; set; }
        public Nullable<System.DateTime> AnswerDate { get; set; }
        public Nullable<int> Reason { get; set; }
        public string ReasonDiff { get; set; }
        public Nullable<int> Status { get; set; }
        public string SSISigner { get; set; }
        public Nullable<int> AnswerForDispatchID { get; set; }
        public Nullable<int> ReceiveAgency { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> SendMethod { get; set; }
        public string ReceiveAgencyDiff { get; set; }
    }
}
