//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Dal.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDocument
    {
        public int ID { get; set; }
        public string FileNo { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public string MimeType { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public byte[] FileData { get; set; }
        public int FileSize { get; set; }
        public string Path { get; set; }
        public Nullable<int> ParentID { get; set; }
        public bool IsFolder { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPublic { get; set; }
        public bool IsReplace { get; set; }
        public bool IsDispatch { get; set; }
        public int Department { get; set; }
        public Nullable<System.DateTime> PromulgatedDate { get; set; }
        public Nullable<int> DocumentTypeCategory { get; set; }
        public string DocumentTypeCategoryDiff { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public string DocumentTypeDiff { get; set; }
        public Nullable<int> AgencyType { get; set; }
        public string AgencyTypeDiff { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public string CreatedByUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> LastWriteTime { get; set; }
    }
}
