//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Dal.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FindAllAccountDomain
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string GiveName { get; set; }
        public string SurName { get; set; }
        public string DisplayName { get; set; }
        public string SamAccountName { get; set; }
        public string UserPrincipalName { get; set; }
        public string EmailAddress { get; set; }
        public string OU1 { get; set; }
        public string DistinguishedName { get; set; }
        public string Descriptions { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string StructuralObjectClasee { get; set; }
        public string Guid { get; set; }
        public string Sid { get; set; }
        public string ContextType { get; set; }
        public Nullable<bool> SmartcardLogonRequired { get; set; }
        public Nullable<bool> PasswordNeverExpires { get; set; }
        public Nullable<bool> PasswordNotRequired { get; set; }
        public Nullable<bool> UserCannotChangePassword { get; set; }
        public Nullable<System.DateTime> LastBadPasswordAttempt { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
        public Nullable<System.DateTime> LastPasswordSet { get; set; }
        public Nullable<int> BadLogonCount { get; set; }
        public Nullable<System.DateTime> AccountExpirationDate { get; set; }
        public Nullable<bool> DelegationPermitted { get; set; }
    }
}
