//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManager.Dal.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public int ObjectID { get; set; }
        public string ObjectName { get; set; }
        public string ObjectTypeCode { get; set; }
        public string ObjectPath { get; set; }
        public string PermissionCode { get; set; }
    }
}
